---
- name: create user accounts
  hosts: all
  become: True
  remote_user: docker
  vars_files:
    - mysecret.yml
  tasks:
    - name: create user from mysecret.yml
      user:
        name: "{{ username }}"
        password: "{{ pw }}"
