---
- name: Configure important user consistently
  hosts: all
  remote_user: docker
  tasks:
    - name: newbie exists with UID 4000
      user:
        name: newboy
        uid: 4200
        state: present
